<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan</name>
  <version>0.7.0</version>
  <description>Metapackage for the RoboPlan motion-planning library.</description>
  <maintainer email="sebas.a.castro@gmail.com">Sebastian Castro</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>roboplan_cartesian_planning</exec_depend>
  <exec_depend>roboplan_common</exec_depend>
  <exec_depend>roboplan_core</exec_depend>
  <exec_depend>roboplan_example_models</exec_depend>
  <exec_depend>roboplan_examples</exec_depend>
  <exec_depend>roboplan_oink</exec_depend>
  <exec_depend>roboplan_rrt</exec_depend>
  <exec_depend>roboplan_simple_ik</exec_depend>
  <exec_depend>roboplan_toppra</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
