[build-system]
requires = ["cmeel[build] >=0.56"]
build-backend = "cmeel.build"

[project]
name = "roboplan"
version = "0.7.0"
description = "Modern robot motion planning library based on Pinocchio."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10,<3.15"
authors = [
    { name = "Sebastian Castro", email = "sebas.a.castro@gmail.com" },
    { name = "Erik Holum", email = "eholum@gmail.com" },
    { name = "Sebastian Jahr", email = "sebastian.jahr@tuta.io" },
    { name = "Jafar Uruç", email = "jafar.uruc@gmail.com" },
]
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "roboplan-cartesian-planning ==0.7.0",
    "roboplan-common ==0.7.0",
    "roboplan-core ==0.7.0",
    "roboplan-example-models ==0.7.0",
    "roboplan-oink ==0.7.0",
    "roboplan-rrt ==0.7.0",
    "roboplan-simple-ik ==0.7.0",
    "roboplan-toppra ==0.7.0",
]

[project.urls]
Homepage = "https://github.com/open-planning/roboplan"

[tool.pixi.package]
publish = true

[tool.pixi.package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[tool.pixi.package.run-dependencies]
roboplan-core = { path = "../roboplan_core" }
roboplan-example-models = { path = "../roboplan_example_models" }
roboplan-oink = { path = "../roboplan_oink" }
roboplan-rrt = { path = "../roboplan_rrt" }
roboplan-simple-ik = { path = "../roboplan_simple_ik" }
roboplan-toppra = { path = "../roboplan_toppra" }
roboplan-cartesian-planning = { path = "../roboplan_cartesian_planning" }

[tool.cmeel]
run-tests = false
has-binaries = false
has-sitelib = false
