[project]
name = "roboplan-examples"
version = "0.7.0"

[tool.pixi.package]
publish = false

[tool.pixi.package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[tool.pixi.package.host-dependencies]
roboplan-cartesian-planning = { path = "../roboplan_cartesian_planning" }
roboplan-core = { path = "../roboplan" }
roboplan-example-models = { path = "../roboplan_example_models" }
roboplan-oink = { path = "../roboplan_oink" }
roboplan-rrt = { path = "../roboplan_rrt" }
roboplan-simple-ik = { path = "../roboplan_simple_ik" }
roboplan-toppra = { path = "../roboplan_toppra" }

[tool.pixi.package.run-dependencies]
matplotlib = ">=3.10.5,<4"
mujoco = ">=3.2,<4"
numpy = "*"
plyfile = ">=1.1,<2"
pycollada = ">=0.9.3,<0.10"
pynput = ">=1.8.2,<2"
robot_descriptions = ">=1.12,<2"
roboplan-cartesian-planning = { path = "../roboplan_cartesian_planning" }
roboplan-core = { path = "../roboplan" }
roboplan-example-models = { path = "../roboplan_example_models" }
roboplan-oink = { path = "../roboplan_oink" }
roboplan-rrt = { path = "../roboplan_rrt" }
roboplan-simple-ik = { path = "../roboplan_simple_ik" }
roboplan-toppra = { path = "../roboplan_toppra" }
tyro = ">=0.9.26,<0.10"
viser = ">=1.0.29,<2"
xacro = ">=2.1.1,<3"
