name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: "0 0 * * *"

  push:
    branches: [main]

  workflow_dispatch:

# Ensures that only one workflow runs at a time for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yml

  build_pypi_wheels:
    name: Wheels
    uses: ./.github/workflows/build-pypi-wheels.yml

  ubuntu_build_and_test:
    name: Bare Ubuntu
    uses: ./.github/workflows/ubuntu_build_and_test.yml

  ros_build_and_test:
    name: ROS
    uses: ./.github/workflows/ros_build_and_test.yml

  pixi_build_and_test:
    name: Pixi
    uses: ./.github/workflows/pixi_build_and_test.yml

  pixi_ros_build_and_test:
    name: Pixi ROS
    uses: ./.github/workflows/pixi_ros_build_and_test.yml

  rrt_benchmarks:
    name: Benchmarks
    uses: ./.github/workflows/rrt_benchmarks.yml
